petfinder/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get '/auth/facebook', as: :sign_in_with_facebook
    # get '/auth/facebook/callback' => 'callbacks#facebook'

    # resources :users, only: [:create, :new]
    # resources :sessions, only: [:new, :create] do
    #   delete :destroy, on: :collection
    # end

    # resources :pets, shallow: true do
    #   resources :sightings, only: [:create, :destroy] do
    #     resources :messages, only: [:create, :destroy]
    #   end
    # end

    # get '/contact' => 'home#contact'
    # post '/contact_submit' => 'home#contact_submit'

  root 'home#index'
  get 'home/about' => 'home#about'
  post '/pets/search', to: 'pets#geo_search'

  resources :users
  resources :sessions, only:[:new,:create] do
    delete :destroy, on: :collection
  end
  resources :sightings
  resources :pets

  resources :home, only: :index

  resources :messages

end

petfinder/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find (session[:user_id]) if user_signed_in?
    @pets = Pet.all
    @hash = Gmaps4rails.build_markers(@pets) do |pet, marker|
      marker.lat pet.latitude
      marker.lng pet.longitude
    end

    @arr = []
    @hash.each do |value|
      @arr.push(value.values.to_a)
    end
    p @arr
  end


end

petfinder/app/helpers/home_helper.rb
module HomeHelper
end

petfinder/app/views/home/about.html.erb
<section id="about">
  <div class="header">
    <div class="title">
      <a class="back-button" href="/">&lt;</a></div>
    About: Find My Pet</div>
  <div id="about-container">
    <p>
      Find My Pet&trade; is a crowd-sourced lost-pet mapper.
    </p>

    <h3>How it works</h3>
    <ul>
      <li>Pet owners report their lost pets</li>
      <li>Community members report sightings of lost pets.</li>
      <li>We map the sightings to help return pets to their owners.</li>
    </ul>

    <h3>Why Find My Pet?</h3>
    <ul>
      <li>70% of households in Canada own a pet</li>
      <li>Every year an estimated 1 million pets are reported lost in Canada.</li>
      <li>Find My Pet exists to reunite lost and lonely pets with their humans.</li>
    </ul>

  </div>
</section>

petfinder/app/views/home/index.html.erb
  <section id="home">
  <div class="header">
    <div class="back-button">
    </div>
    <div class="title" id="home-title">
      <span style="font-size: xx-large;"><%= fa_icon "paw"%></span>&nbsp;&nbsp;&nbsp;Welcome <%= @user.first_name if user_signed_in? %>
    </div>
  </div>
  <ul class="nav nav-stacked">
    <div role="presentation" class="nav-title divider">MAKE A REPORT</div>
    <li role="presentation"><a id="lost-pet" href="/pets/new">Report Your Lost Pet</a></li>
    <li role="presentation"><a id="found-pet" href="/sightings/new">Found/Sighted Pet</a></li>
    <div role="presentation" class="nav-title divider">ACCOUNT</div>
    <li role="presentation"><%# link_to "My Report", user_path(@user) %></li>
    <% if user_signed_in? %>
      <li role="presentation"><a id="reports" href="/users/<%= @user.id %>">My Reports</a></li>
      <li role="presentation"><a id="messages" href="/messages/new">Messages</a></li>
      <li role="presentation"><a id="settings" href="#">Settings</a></li>
      <li role="presentation"><%= link_to "Log out", sessions_path	, method: :delete %></li>
    <% else  %>
      <li role="presentation"><a id="login" href="/sessions/new">Login</a></li>
      <li role="presentation"><a id="signup" href="/users/new">Sign Up</a></li>
    <% end %>
    <li role="presentation"><a id="about-us" href="home/about">About find my pet</a></li>

  </ul>
</section>